# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qVgz6JtghpUW37GVn_SYh3LRlzIQq6B
"""

import numpy as np

d1 = np.array([1,2,3,4,5,6])
d2 = np.array([[1,2,3], [4,5,6]])

sum_d1 = np.sum(d1)
sum_d2 = np.sum(d2)
mean_d1 = np.mean(d1)
mean_d2 = np.mean(d2)
prod_d1 = np.prod(d1)
prod_d2 = np.prod(d2)

print("1D massiv:", d1)
print("2D massiv:\n", d2)
print("1D yig'indisi:", sum_d1)
print("1D o'rtachasi:", mean_d1)
print("1D ko'paytmasi:", prod_d1)
print("2D yig'indisi:", sum_d2)
print("2D o'rtachasi:", mean_d2)
print("2D ko'paytmasi:", prod_d2)

import pandas as pd

data = {
    "Name": [ "Anvarjon", "Bunyod", "Muhammadayubxon", "Muhammadrizo", "Javohir",
             "Hakimjon", "Farruxbek", "Jasurbek", "Gulshanoy", "Zufarbek"],
    "Age": [ 18, 19, 19, 21, 19, 19, 19, 21, 19, 21, ],
    "City": [ "Farg'ona", "Farg'ona", "Farg'ona", "Qo'shtepa", "Quvasoy",
             "Farg'ona", "Chust", "Farg'ona", "Farg'ona", "Farg'ona"]
}
pdf = pd.DataFrame(data)

mahalliy = pdf[pdf["City"] == "Farg'ona"]


print("Fag'onaliklar soni",len(mahalliy), "\n", mahalliy)